Feat/census exportation
silvglad/decide pull request #10
Opened 2023-11-08 09:00 UTC by claugp06

Posibilidad de exportar el csv con los datos del censo

2023-11-08 09:12 UTC, MarioArocaPaez requested changes
En principio, parece que todo está bien y debería funcionar correctamente, pero hay algunas cositas importantes.

Primero, es crucial destacar que no podemos hacer un PR a la rama master directamente desde una rama de feature. Primero debemos hacerlo a la rama develop y luego a master. :eyeglasses: :point_up_2:

Además, si no me equivoco, sería necesario añadir pruebas (tests) y creo que sería más lógico para la aplicación que solo los administradores puedan extraer el archivo CSV. Como ejemplo, podéis ver en el módulo de autenticación cómo se implementa para que solo un administrador pueda realizar esta operación

2023-11-08 15:00 UTC, 3ralon requested changes
¡Ha quedado de lujo la vista!. Por lo demás, coincido con lo que ha comentado @MarioArocaPaez en la [review anterior](https://github.com/3ralon/decide/pull/10#pullrequestreview-1719756806).

2023-11-08 15:00 UTC, 3ralon commented on decide/census/views.py
> +    response = HttpResponse(
¡Está genial el código! Podría ser interesante utilizar `StreamingHttpResponse` en lugar de `HttpResponse` en caso de que el censo fuese muy grande para no tener problemas con el timeout.

Hay más información en la doc. oficial de django, en concreto en [esta página](https://docs.djangoproject.com/en/4.2/howto/outputting-csv/#streaming-large-csv-files).

2023-11-13 12:16 UTC, perealberto reviewed
Parece que todo está bien. ¿Vais a añadir más cambios?

2023-11-13 12:17 UTC, laurolmer commented
> Parece que todo está bien. ¿Vais a añadir más cambios?

No creo.

2023-11-13 12:19 UTC, 3ralon approved these changes
De acuerdo, si los tests se pasan sin problemas y está hecho todo lo de esta feature, doy mi aprobado 😄 !

2023-11-13 12:41 UTC, MarioArocaPaez approved these changes

2023-11-13 14:24 UTC, merged