feat: Register para usuarios normales
silvglad/decide pull request #6
Opened 2023-11-05 12:31 UTC by MarioArocaPaez

Añadida la posibilidad de que un usuario se registre en la aplicación sin ser administrador por medio de authentication/register

2023-11-05 16:00 UTC, perealberto reviewed
Todo parece correcto 👍 . Es genial que el form se cree solo con Django.
¿Probaste que el _superuser_ siga pudiendo crear usuarios y que no se rompió nada?

@MarioArocaPaez

2023-11-05 16:07 UTC, MarioArocaPaez commented
Si, el superuser puede crear también usuarios, no hay problema

2023-11-05 16:25 UTC, 3ralon requested changes
Okey, si no rompe nada perfecto 💯 . Pero, antes de aceptar la PR ¡que no se te olvide hacer los **tests**! xd
@MarioArocaPaez

2023-11-13 08:50 UTC, 3ralon approved these changes
Todo parece en orden. Perfecto 😄, ahora ya podemos hacer merge.

2023-11-13 08:52 UTC, merged